const fs = require("fs");
const path = require('path');
const inquirer = require("inquirer");
const generateMarkdown = require("./utils/generateMarkdown");

// array of questions for user
const questions = [
    {
        type: 'input',
        name: 'title',
        message: 'What the title of the project',
      },

];

// function to write README file
function writeToFile(fileName, info) {
    fs.writeFile(fileName, info, (err) => {
               
        if (err) {
            console.error(err);
        } else {
            console.log('Answers saved to file.txt');
        }
    });

}

// function to initialize program
function init() {
    inquirer.prompt(questions)
    .then((answers) => {
        // function call to write file.txt with text generated by module 
        writeToFile ("file.txt", generateMarkdown(answers));
    })

}

// function call to initialize program
init();

