const fs = require("fs");
const path = require('path');
const inquirer = require("inquirer");
const generateMarkdown = require("./utils/generateMarkdown");

// array of questions for user
const questions = [
    {
        type: 'input',
        name: 'title',
        message: 'What is the Title of the project ?',
    },
    {
        type: 'input',
        name: 'description',
        message: 'Please Describe your project : ',
    },
    {
        type: 'input',
        name: 'Instalation',
        message: 'Please give information regarding the Instalation : ',
    },
    {
        type: 'input',
        name: 'Usage',
        message: 'Please give information about Usage : ',
    },
    {
        type: 'list',
        name: 'License',
        choices: ['none', 'MIT License', 'Apache License 2.0'],
        message: 'Please select the License : ',
    },
    {
        type: 'input',
        name: 'Contributing',
        message: 'Please give information about Contributing : ',
    },
    {
        type: 'input',
        name: 'Tests',
        message: 'Please give information about Tests : ',
    },
    

];

// function to write README file
function writeToFile(fileName, info) {
    fs.writeFile(fileName, info, (err) => {
        if (err) {
            console.error(err);
        } else {
            console.log('Answers saved to file.txt');
        }
    });

}

// function to initialize program
function init() {
    inquirer.prompt(questions)
    .then((answers) => {
        // function call to write file.txt with text generated by module 
        writeToFile ("test.md", generateMarkdown(answers));
    })

}

// function call to initialize program
init();

